// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";
import type { PortfolioPortfolioState } from "./types.js";

export interface ContractEvents<
  Type extends MetadataType,
> extends GenericContractEvents<Type> {
  /**
   *
   *
   **/
  OwnershipTransferred: GenericContractEvent<
    "OwnershipTransferred",
    {
      /**
       *
       * @indexed: true
       **/
      previousOwner: H160;
      /**
       *
       * @indexed: true
       **/
      newOwner: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  PortfolioInitialized: GenericContractEvent<
    "PortfolioInitialized",
    {
      /**
       *
       * @indexed: false
       **/
      owner: H160;
      /**
       *
       * @indexed: false
       **/
      deploymentTimestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      indexBaseValue: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  PortfolioStateChanged: GenericContractEvent<
    "PortfolioStateChanged",
    {
      /**
       *
       * @indexed: false
       **/
      oldState: PortfolioPortfolioState;
      /**
       *
       * @indexed: false
       **/
      newState: PortfolioPortfolioState;
      /**
       *
       * @indexed: false
       **/
      changedBy: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  FeeConfigurationUpdated: GenericContractEvent<
    "FeeConfigurationUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldBuyFee: number;
      /**
       *
       * @indexed: false
       **/
      newBuyFee: number;
      /**
       *
       * @indexed: false
       **/
      oldSellFee: number;
      /**
       *
       * @indexed: false
       **/
      newSellFee: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  ContractReferenceUpdated: GenericContractEvent<
    "ContractReferenceUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      contractType: number;
      /**
       *
       * @indexed: false
       **/
      newAddress: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  OwnershipTransferProposed: GenericContractEvent<
    "OwnershipTransferProposed",
    {
      /**
       *
       * @indexed: true
       **/
      currentOwner: H160;
      /**
       *
       * @indexed: true
       **/
      proposedOwner: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  EmergencyPause: GenericContractEvent<
    "EmergencyPause",
    {
      /**
       *
       * @indexed: false
       **/
      paused: boolean;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  IndexValueUpdated: GenericContractEvent<
    "IndexValueUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldValue: bigint;
      /**
       *
       * @indexed: false
       **/
      newValue: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingAdded: GenericContractEvent<
    "TokenHoldingAdded",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      amount: bigint;
      /**
       *
       * @indexed: false
       **/
      targetWeightBp: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingRemoved: GenericContractEvent<
    "TokenHoldingRemoved",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      finalAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenHoldingUpdated: GenericContractEvent<
    "TokenHoldingUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      oldAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      newAmount: bigint;
      /**
       *
       * @indexed: false
       **/
      oldWeight: number;
      /**
       *
       * @indexed: false
       **/
      newWeight: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;
}
