// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from "dedot/types";
import type { InkGenericContractApi, WithLazyStorage } from "dedot/contracts";
import type { SubstrateApi } from "dedot/chaintypes";
import type { InkPrimitivesLangError, Portfolio } from "./types.js";
import { ContractQuery } from "./query.js";
import { ContractTx } from "./tx.js";
import { ConstructorQuery } from "./constructor-query.js";
import { ConstructorTx } from "./constructor-tx.js";
import { ContractEvents } from "./events.js";

export * from "./types.js";

/**
 * @name: PortfolioContractApi
 * @contractName: portfolio
 * @contractVersion: 0.1.0
 * @authors: 3dln <ashcan@3dln.com>
 * @language: ink! 6.0.0-beta.1
 **/
export interface PortfolioContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: "ink";
  query: ContractQuery<"ink">;
  tx: ContractTx<"ink">;
  constructorQuery: ConstructorQuery<"ink">;
  constructorTx: ConstructorTx<PortfolioContractApi, "ink">;
  events: ContractEvents<"ink">;
  storage: {
    root(): Promise<Portfolio>;
    lazy(): WithLazyStorage<Portfolio>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: Portfolio;
    LazyStorage: WithLazyStorage<Portfolio>;
    LangError: InkPrimitivesLangError;
  };
}
