// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  InkPrimitivesLangError,
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
  PortfolioError,
  PortfolioTokenHolding,
  PortfolioPortfolioComposition,
} from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<H160, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x78a510ce
   **/
  getPendingOwner: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x3d1e8968
   **/
  getState: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<PortfolioPortfolioState, ContractCallResult>
    >,
    Type
  >;

  /**
   * Alias for get_state
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9116c86c
   **/
  getPortfolioState: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<PortfolioPortfolioState, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2c258e50
   **/
  getDeploymentTimestamp: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x114748a6
   **/
  getTotalTokensHeld: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x96436f0b
   **/
  getHeldTokenIds: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<number>, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x23e4a85f
   **/
  isEmergencyPaused: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x12136f86
   **/
  getFeeConfig: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<PortfolioFeeConfiguration, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xc7a8291f
   **/
  getTotalFeesCollected: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {H160} newOwner
   * @param {ContractCallOptions} options
   *
   * @selector 0xd8fae5bd
   **/
  proposeOwnershipTransfer: GenericContractQueryCall<
    (
      newOwner: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xb55be9f0
   **/
  acceptOwnership: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07144662
   **/
  cancelOwnershipTransfer: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {PortfolioPortfolioState} newState
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x62fac83c
   **/
  setState: GenericContractQueryCall<
    (
      newState: PortfolioPortfolioState,
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x4ec112d9
   **/
  emergencyPause: GenericContractQueryCall<
    (
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0xdacb444b
   **/
  emergencyResume: GenericContractQueryCall<
    (
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {PortfolioFeeConfiguration} newConfig
   * @param {ContractCallOptions} options
   *
   * @selector 0xbe172e69
   **/
  setFeeConfig: GenericContractQueryCall<
    (
      newConfig: PortfolioFeeConfiguration,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0xd753ec74
   **/
  setRegistryContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x2fc3cfae
   **/
  setTokenContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x56062dea
   **/
  setOracleContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x46e77b11
   **/
  setUsdcContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0x00e16ab8
   **/
  setStakingContract: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractCallOptions} options
   *
   * @selector 0xa4ec73da
   **/
  setPortfolioManager: GenericContractQueryCall<
    (
      addr: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x541952c6
   **/
  getRegistryContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xad4a397f
   **/
  getTokenContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8b6aff5f
   **/
  getDexContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x47d22829
   **/
  getOracleContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7e02b7b2
   **/
  getUsdcContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x01b9cd68
   **/
  getStakingContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xefcc843b
   **/
  getPortfolioManager: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {bigint} amount
   * @param {number} targetWeightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0x8c8c0dbb
   **/
  addTokenHolding: GenericContractQueryCall<
    (
      tokenId: number,
      amount: bigint,
      targetWeightBp: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Remove a token holding. Can be called by owner, manager, or Registry (for tier removal).
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x8499ff26
   **/
  removeTokenHolding: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newTargetWeightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0xcb447ba5
   **/
  updateTokenHolding: GenericContractQueryCall<
    (
      tokenId: number,
      newAmount: bigint,
      newTargetWeightBp: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x1aa480ab
   **/
  getTokenHolding: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioTokenHolding | undefined,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x6327cf7d
   **/
  holdsToken: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x95c95f2d
   **/
  getPortfolioComposition: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        PortfolioPortfolioComposition,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xfe250e33
   **/
  getTokenAmount: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xb07c6e53
   **/
  getTokenTargetWeight: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xe7bdd0ac
   **/
  getAllHoldings: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<[number, bigint]>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractCallOptions} options
   *
   * @selector 0x6e4c60a4
   **/
  getHoldingsPaginated: GenericContractQueryCall<
    (
      offset: number,
      limit: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<[number, bigint]>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xfe275351
   **/
  getAllTargetWeights: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<[number, number]>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractCallOptions} options
   *
   * @selector 0x111dc9f4
   **/
  getTargetWeightsPaginated: GenericContractQueryCall<
    (
      offset: number,
      limit: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<[number, number]>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf5ecafdc
   **/
  getTotalTargetWeight: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xc4860b34
   **/
  hasHoldings: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6a0fdd74
   **/
  getPortfolioStats: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[number, number, number], ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {Array<[number, bigint, number]>} holdingsData
   * @param {ContractCallOptions} options
   *
   * @selector 0xe0e682d6
   **/
  addMultipleHoldings: GenericContractQueryCall<
    (
      holdingsData: Array<[number, bigint, number]>,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, PortfolioError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {Array<[number, bigint]>} updates
   * @param {ContractCallOptions} options
   *
   * @selector 0xc6ac54cd
   **/
  updateMultipleAmounts: GenericContractQueryCall<
    (
      updates: Array<[number, bigint]>,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, PortfolioError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {number} maxTokens
   * @param {ContractCallOptions} options
   *
   * @selector 0x20cbe039
   **/
  setMaxTokens: GenericContractQueryCall<
    (
      maxTokens: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbba8005a
   **/
  getMaxTokens: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {number} count
   * @param {ContractCallOptions} options
   *
   * @selector 0xbd857de4
   **/
  canAddTokens: GenericContractQueryCall<
    (
      count: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4391adfb
   **/
  validateWeightAllocation: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<boolean, PortfolioError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xb49fd71c
   **/
  getRemainingWeightCapacity: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x19c35771
   **/
  getCurrentIndexValue: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2abe9859
   **/
  getIndexBaseMetrics: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        [bigint, bigint, bigint, boolean],
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4d7bbe62
   **/
  getIndexSummary: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[bigint, bigint, number, bigint], PortfolioError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xf6b2f5b5
   **/
  getIndexPerformance: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, PortfolioError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6c0e9ae6
   **/
  isIndexTrackingEnabled: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xff089403
   **/
  isIndexValueStale: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xdcfa4e18
   **/
  getIndexUpdateAge: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {boolean} enabled
   * @param {ContractCallOptions} options
   *
   * @selector 0x720eed85
   **/
  setIndexTracking: GenericContractQueryCall<
    (
      enabled: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x8b4a4890
   **/
  setIndexBaseValue: GenericContractQueryCall<
    (
      newValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Initialize base portfolio value (owner only, once)
   *
   * @param {bigint} initialValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xf43ecec5
   **/
  initializeBasePortfolioValue: GenericContractQueryCall<
    (
      initialValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Emergency reset index base value (owner only)
   *
   * @param {bigint} newBaseValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x45ce6272
   **/
  emergencyResetBaseValue: GenericContractQueryCall<
    (
      newBaseValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {bigint} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xd7460457
   **/
  setLiquidityBuffer: GenericContractQueryCall<
    (
      newValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xc861a01c
   **/
  setMaxSinglePosition: GenericContractQueryCall<
    (
      newValue: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7352ac09
   **/
  getMaxSinglePosition: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x6cc09ca6
   **/
  setMaxSlippage: GenericContractQueryCall<
    (
      newValue: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xbb255b5d
   **/
  getMaxSlippage: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractCallOptions} options
   *
   * @selector 0xeba65fa0
   **/
  setRebalanceThreshold: GenericContractQueryCall<
    (
      newValue: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x73fb1c42
   **/
  getRebalanceThreshold: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x88198af7
   **/
  getUsdcBalance: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Update a token holding (called by portfolio_manager during rebalancing/buy/sell)
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newWeight
   * @param {ContractCallOptions} options
   *
   * @selector 0xa2cc399d
   **/
  updateHoldingFromManager: GenericContractQueryCall<
    (
      tokenId: number,
      newAmount: bigint,
      newWeight: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Update USDC balance (called by portfolio_manager)
   *
   * @param {bigint} delta
   * @param {boolean} isAdd
   * @param {ContractCallOptions} options
   *
   * @selector 0xdff35bd7
   **/
  updateUsdcBalanceFromManager: GenericContractQueryCall<
    (
      delta: bigint,
      isAdd: boolean,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Add to total fees collected (called by portfolio_manager)
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x990ca588
   **/
  addFeesFromManager: GenericContractQueryCall<
    (
      amount: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Update index value from manager with calculated portfolio value
   *
   * @param {bigint} currentPortfolioValue
   * @param {ContractCallOptions} options
   *
   * @selector 0x37546322
   **/
  updateIndexFromManager: GenericContractQueryCall<
    (
      currentPortfolioValue: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], PortfolioError>, ContractCallResult>
    >,
    Type
  >;
}
