// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type {
  PortfolioPortfolioState,
  PortfolioFeeConfiguration,
} from "./types.js";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   *
   * @param {H160} newOwner
   * @param {ContractTxOptions} options
   *
   * @selector 0xd8fae5bd
   **/
  proposeOwnershipTransfer: GenericContractTxCall<
    (
      newOwner: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xb55be9f0
   **/
  acceptOwnership: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x07144662
   **/
  cancelOwnershipTransfer: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {PortfolioPortfolioState} newState
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x62fac83c
   **/
  setState: GenericContractTxCall<
    (
      newState: PortfolioPortfolioState,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x4ec112d9
   **/
  emergencyPause: GenericContractTxCall<
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0xdacb444b
   **/
  emergencyResume: GenericContractTxCall<
    (
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {PortfolioFeeConfiguration} newConfig
   * @param {ContractTxOptions} options
   *
   * @selector 0xbe172e69
   **/
  setFeeConfig: GenericContractTxCall<
    (
      newConfig: PortfolioFeeConfiguration,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0xd753ec74
   **/
  setRegistryContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0x2fc3cfae
   **/
  setTokenContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0xb53ae601
   **/
  setDexContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0x56062dea
   **/
  setOracleContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0x46e77b11
   **/
  setUsdcContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0x00e16ab8
   **/
  setStakingContract: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {H160} addr
   * @param {ContractTxOptions} options
   *
   * @selector 0xa4ec73da
   **/
  setPortfolioManager: GenericContractTxCall<
    (addr: H160, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {bigint} amount
   * @param {number} targetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0x8c8c0dbb
   **/
  addTokenHolding: GenericContractTxCall<
    (
      tokenId: number,
      amount: bigint,
      targetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Remove a token holding. Can be called by owner, manager, or Registry (for tier removal).
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0x8499ff26
   **/
  removeTokenHolding: GenericContractTxCall<
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newTargetWeightBp
   * @param {ContractTxOptions} options
   *
   * @selector 0xcb447ba5
   **/
  updateTokenHolding: GenericContractTxCall<
    (
      tokenId: number,
      newAmount: bigint,
      newTargetWeightBp: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {Array<[number, bigint, number]>} holdingsData
   * @param {ContractTxOptions} options
   *
   * @selector 0xe0e682d6
   **/
  addMultipleHoldings: GenericContractTxCall<
    (
      holdingsData: Array<[number, bigint, number]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {Array<[number, bigint]>} updates
   * @param {ContractTxOptions} options
   *
   * @selector 0xc6ac54cd
   **/
  updateMultipleAmounts: GenericContractTxCall<
    (
      updates: Array<[number, bigint]>,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} maxTokens
   * @param {ContractTxOptions} options
   *
   * @selector 0x20cbe039
   **/
  setMaxTokens: GenericContractTxCall<
    (
      maxTokens: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {boolean} enabled
   * @param {ContractTxOptions} options
   *
   * @selector 0x720eed85
   **/
  setIndexTracking: GenericContractTxCall<
    (
      enabled: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x8b4a4890
   **/
  setIndexBaseValue: GenericContractTxCall<
    (
      newValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Initialize base portfolio value (owner only, once)
   *
   * @param {bigint} initialValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xf43ecec5
   **/
  initializeBasePortfolioValue: GenericContractTxCall<
    (
      initialValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Emergency reset index base value (owner only)
   *
   * @param {bigint} newBaseValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x45ce6272
   **/
  emergencyResetBaseValue: GenericContractTxCall<
    (
      newBaseValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {bigint} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xd7460457
   **/
  setLiquidityBuffer: GenericContractTxCall<
    (
      newValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xc861a01c
   **/
  setMaxSinglePosition: GenericContractTxCall<
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x6cc09ca6
   **/
  setMaxSlippage: GenericContractTxCall<
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   *
   * @param {number} newValue
   * @param {ContractTxOptions} options
   *
   * @selector 0xeba65fa0
   **/
  setRebalanceThreshold: GenericContractTxCall<
    (
      newValue: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update a token holding (called by portfolio_manager during rebalancing/buy/sell)
   *
   * @param {number} tokenId
   * @param {bigint} newAmount
   * @param {number} newWeight
   * @param {ContractTxOptions} options
   *
   * @selector 0xa2cc399d
   **/
  updateHoldingFromManager: GenericContractTxCall<
    (
      tokenId: number,
      newAmount: bigint,
      newWeight: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update USDC balance (called by portfolio_manager)
   *
   * @param {bigint} delta
   * @param {boolean} isAdd
   * @param {ContractTxOptions} options
   *
   * @selector 0xdff35bd7
   **/
  updateUsdcBalanceFromManager: GenericContractTxCall<
    (
      delta: bigint,
      isAdd: boolean,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Add to total fees collected (called by portfolio_manager)
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x990ca588
   **/
  addFeesFromManager: GenericContractTxCall<
    (
      amount: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update index value from manager with calculated portfolio value
   *
   * @param {bigint} currentPortfolioValue
   * @param {ContractTxOptions} options
   *
   * @selector 0x37546322
   **/
  updateIndexFromManager: GenericContractTxCall<
    (
      currentPortfolioValue: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
