// Generated by dedot cli

import type { H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type PortfolioTokenHolding = {
  amount: bigint;
  targetWeightBp: number;
  lastRebalance: bigint;
  feesCollected: bigint;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Portfolio = {
  owner: H160;
  pendingOwner?: H160 | undefined;
  state: PortfolioPortfolioState;
  deploymentTimestamp: bigint;
  holdings: { get(arg: number): Promise<PortfolioTokenHolding | undefined> };
  heldTokenIds: Array<number>;
  totalTokensHeld: number;
  indexBaseValue: bigint;
  basePortfolioValue: bigint;
  currentIndexValue: bigint;
  lastIndexUpdate: bigint;
  indexTrackingEnabled: boolean;
  feeConfig: PortfolioFeeConfiguration;
  totalFeesCollected: bigint;
  registryContract?: H160 | undefined;
  tokenContract?: H160 | undefined;
  dexContract?: H160 | undefined;
  oracleContract?: H160 | undefined;
  usdcContract?: H160 | undefined;
  stakingContract?: H160 | undefined;
  portfolioManager?: H160 | undefined;
  maxTokens: number;
  minPortfolioValue: bigint;
  rebalanceThresholdBp: number;
  emergencyPaused: boolean;
  minLiquidityBuffer: bigint;
  usdcBalance: bigint;
  maxSinglePositionBp: number;
  maxSlippageBp: number;
};

export type PortfolioPortfolioState =
  | "Active"
  | "Paused"
  | "Maintenance"
  | "Emergency";

export type PortfolioFeeConfiguration = {
  buyFeeBp: number;
  sellFeeBp: number;
  streamingFeeBp: number;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type PortfolioError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed"
  | "InvalidParameters"
  | "ReentrantCall"
  | "MaxTokensReached"
  | "NoPendingOwner";

export type PortfolioPortfolioComposition = {
  totalTokens: number;
  totalValue: bigint;
  holdings: Array<[number, PortfolioTokenHolding]>;
};
