// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractEvents,
  GenericContractEvent,
  MetadataType,
} from "dedot/contracts";
import type { RegistryTier, RegistryRole, RegistryError } from "./types.js";

export interface ContractEvents<
  Type extends MetadataType,
> extends GenericContractEvents<Type> {
  /**
   *
   *
   **/
  CrossContractCallFailed: GenericContractEvent<
    "CrossContractCallFailed",
    {
      /**
       *
       * @indexed: false
       **/
      targetContract: string;
      /**
       *
       * @indexed: false
       **/
      functionName: string;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  OwnershipTransferAccepted: GenericContractEvent<
    "OwnershipTransferAccepted",
    {
      /**
       *
       * @indexed: true
       **/
      oldOwner: H160;
      /**
       *
       * @indexed: true
       **/
      newOwner: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  OwnershipTransferProposed: GenericContractEvent<
    "OwnershipTransferProposed",
    {
      /**
       *
       * @indexed: true
       **/
      currentOwner: H160;
      /**
       *
       * @indexed: true
       **/
      proposedOwner: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  OwnershipTransferCancelled: GenericContractEvent<
    "OwnershipTransferCancelled",
    {
      /**
       *
       * @indexed: true
       **/
      currentOwner: H160;
      /**
       *
       * @indexed: true
       **/
      cancelledOwner: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenAdded: GenericContractEvent<
    "TokenAdded",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: H160;
      /**
       *
       * @indexed: false
       **/
      oracleContract: H160;
      /**
       *
       * @indexed: false
       **/
      initialTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      addedBy: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  RoleGranted: GenericContractEvent<
    "RoleGranted",
    {
      /**
       *
       * @indexed: true
       **/
      role: RegistryRole;
      /**
       *
       * @indexed: true
       **/
      account: H160;
      /**
       *
       * @indexed: false
       **/
      grantedBy: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  RoleRevoked: GenericContractEvent<
    "RoleRevoked",
    {
      /**
       *
       * @indexed: true
       **/
      role: RegistryRole;
      /**
       *
       * @indexed: true
       **/
      account: H160;
      /**
       *
       * @indexed: false
       **/
      revokedBy: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenRemoved: GenericContractEvent<
    "TokenRemoved",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: H160;
      /**
       *
       * @indexed: false
       **/
      tier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      removedBy: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenUpdated: GenericContractEvent<
    "TokenUpdated",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      balance: bigint;
      /**
       *
       * @indexed: false
       **/
      weightInvestment: number;
      /**
       *
       * @indexed: false
       **/
      oldTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      newTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      updatedBy: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  OperationFailed: GenericContractEvent<
    "OperationFailed",
    {
      /**
       *
       * @indexed: false
       **/
      operation: string;
      /**
       *
       * @indexed: false
       **/
      error: RegistryError;
      /**
       *
       * @indexed: false
       **/
      caller: H160;
    },
    Type
  >;

  /**
   *
   *
   **/
  OracleCallFailed: GenericContractEvent<
    "OracleCallFailed",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      functionName: string;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenTierChanged: GenericContractEvent<
    "TokenTierChanged",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: H160;
      /**
       *
       * @indexed: false
       **/
      oldTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      newTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      marketCap: bigint;
      /**
       *
       * @indexed: false
       **/
      volume: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  ActiveTierShifted: GenericContractEvent<
    "ActiveTierShifted",
    {
      /**
       *
       * @indexed: false
       **/
      oldTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      newTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      triggerReason: string;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      tokensQualifying: number;
      /**
       *
       * @indexed: false
       **/
      totalTokens: number;
    },
    Type
  >;

  /**
   *
   *
   **/
  GracePeriodStarted: GenericContractEvent<
    "GracePeriodStarted",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      currentTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      pendingTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      graceEndTime: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  GracePeriodUpdated: GenericContractEvent<
    "GracePeriodUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      oldPeriodMs: bigint;
      /**
       *
       * @indexed: false
       **/
      newPeriodMs: bigint;
      /**
       *
       * @indexed: false
       **/
      updatedBy: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  EmergencyTierOverride: GenericContractEvent<
    "EmergencyTierOverride",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: true
       **/
      tokenContract: H160;
      /**
       *
       * @indexed: false
       **/
      oldTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      newTier: RegistryTier;
      /**
       *
       * @indexed: false
       **/
      overriddenBy: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      reason: string;
    },
    Type
  >;

  /**
   *
   *
   **/
  TierThresholdsUpdated: GenericContractEvent<
    "TierThresholdsUpdated",
    {
      /**
       *
       * @indexed: false
       **/
      updatedBy: H160;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
      /**
       *
       * @indexed: false
       **/
      newUsdRate: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  TokenRemovedFromIndex: GenericContractEvent<
    "TokenRemovedFromIndex",
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: number;
      /**
       *
       * @indexed: false
       **/
      timestamp: bigint;
    },
    Type
  >;
}
