// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160, Result } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from "dedot/contracts";
import type {
  RegistryRole,
  RegistryError,
  InkPrimitivesLangError,
  RegistryTier,
  RegistryTierThresholds,
  RegistryStoredTokenData,
  RegistryEnrichedTokenData,
  RegistryTokenData,
} from "./types.js";

export interface ContractQuery<
  Type extends MetadataType,
> extends GenericContractQuery<Type> {
  /**
   * Grant a role to an account (owner only)
   *
   * @param {RegistryRole} role
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x2aabfab5
   **/
  grantRole: GenericContractQueryCall<
    (
      role: RegistryRole,
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Revoke a role from an account (owner only)
   *
   * @param {RegistryRole} role
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x35e1ef4a
   **/
  revokeRole: GenericContractQueryCall<
    (
      role: RegistryRole,
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Check if an account has a specific role
   *
   * @param {RegistryRole} role
   * @param {H160} account
   * @param {ContractCallOptions} options
   *
   * @selector 0x8d194a68
   **/
  hasRole: GenericContractQueryCall<
    (
      role: RegistryRole,
      account: H160,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Add a new token to the registry with automatic tier calculation.
   * Blocked when contract is paused.
   *
   * @param {H160} tokenContract
   * @param {H160} oracleContract
   * @param {ContractCallOptions} options
   *
   * @selector 0x84731716
   **/
  addToken: GenericContractQueryCall<
    (
      tokenContract: H160,
      oracleContract: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Update token balance and investment data with automatic tier recalculation.
   * Blocked when contract is paused.
   *
   * @param {number} tokenId
   * @param {bigint} balance
   * @param {number} weightInvestment
   * @param {ContractCallOptions} options
   *
   * @selector 0x90c3ef3a
   **/
  updateToken: GenericContractQueryCall<
    (
      tokenId: number,
      balance: bigint,
      weightInvestment: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Remove a token from the registry.
   * Blocked when contract is paused.
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xc964c4ec
   **/
  removeToken: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Calculate tier for a token based on market cap and volume
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xa755bec5
   **/
  calculateTokenTier: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryTier, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Manually update tier for a specific token (owner only)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xb11eb1ae
   **/
  updateTokenTier: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryTier, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Emergency tier override - bypasses grace period (owner only).
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {number} tokenId
   * @param {RegistryTier} newTier
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0xe67d97ff
   **/
  emergencyTierOverride: GenericContractQueryCall<
    (
      tokenId: number,
      newTier: RegistryTier,
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Emergency tier override to calculated tier - bypasses grace period (owner only)
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {number} tokenId
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x5b5a3d00
   **/
  emergencyTierOverrideToCalculated: GenericContractQueryCall<
    (
      tokenId: number,
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryTier, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Clear pending tier change (owner only)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x53bba34a
   **/
  clearPendingTierChange: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set grace period duration (owner only)
   *
   * @param {bigint} periodMs
   * @param {ContractCallOptions} options
   *
   * @selector 0x86200a8b
   **/
  setGracePeriod: GenericContractQueryCall<
    (
      periodMs: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get current grace period duration in milliseconds
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8ec39146
   **/
  getGracePeriod: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get grace period duration in days (for convenience)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xae9bc01a
   **/
  getGracePeriodDays: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get grace period duration in hours (for convenience)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x7dc7dbbe
   **/
  getGracePeriodHours: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;

  /**
   * Get grace period limits (min/max allowed)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x22f73d30
   **/
  getGracePeriodLimits: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<[bigint, bigint], ContractCallResult>
    >,
    Type
  >;

  /**
   * Calculate grace period end time for a token
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x8eee05ca
   **/
  getGracePeriodEndTime: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Check how much time is left in grace period for a token
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x2645f97f
   **/
  getGracePeriodRemaining: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Check if grace period has expired for a token
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x2f44c657
   **/
  isGracePeriodExpired: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Batch update tiers for tokens with pagination.
   * Returns number of tokens updated in this batch.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8646ff68
   **/
  refreshAllTiers: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Paginated version of refresh_all_tiers.
   * `offset`: number of token IDs to skip from the start (0-based),
   * `limit`: maximum number of token IDs to process.
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractCallOptions} options
   *
   * @selector 0xbae7b4f9
   **/
  refreshTiersPaginated: GenericContractQueryCall<
    (
      offset: number,
      limit: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Process tokens with expired grace periods (updated to use dynamic grace period)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x39150c26
   **/
  processGracePeriods: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Paginated grace-period processing.
   * `offset`: number of token IDs to skip from the start (0-based),
   * `limit`: maximum number of token IDs to scan.
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractCallOptions} options
   *
   * @selector 0xa9695f4f
   **/
  processGracePeriodsPaginated: GenericContractQueryCall<
    (
      offset: number,
      limit: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<number, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get current distribution of tokens across tiers
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xdf68aa7e
   **/
  getTierDistribution: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<[RegistryTier, number]>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Check if 80% rule should trigger tier shift
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xda628aff
   **/
  shouldShiftTier: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<RegistryTier | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Execute tier shift (automatic or manual)
   * Manual tier shift - owner only
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {RegistryTier} newTier
   * @param {string} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0x71f99599
   **/
  shiftActiveTier: GenericContractQueryCall<
    (
      newTier: RegistryTier,
      reason: string,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set DOT/USD oracle contract (owner only)
   *
   * @param {H160} oracleContract
   * @param {ContractCallOptions} options
   *
   * @selector 0x819b20a3
   **/
  setDotUsdOracle: GenericContractQueryCall<
    (
      oracleContract: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get current DOT/USD oracle contract
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x14ae30fd
   **/
  getDotUsdOracle: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Update tier thresholds in USD (owner only)
   *
   * @param {RegistryTierThresholds} thresholds
   * @param {ContractCallOptions} options
   *
   * @selector 0xe2d49881
   **/
  setTierThresholds: GenericContractQueryCall<
    (
      thresholds: RegistryTierThresholds,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get current tier thresholds
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x19a4c86d
   **/
  getTierThresholds: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<RegistryTierThresholds, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get current active tier
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x700681c2
   **/
  getActiveTier: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<RegistryTier, ContractCallResult>>,
    Type
  >;

  /**
   * Get last tier change timestamp
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xd930ef30
   **/
  getLastTierChange: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get current USD to plancks conversion rate from oracle
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x80c4ad2d
   **/
  getCurrentUsdRate: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get enhanced token data with tier information
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x6c09403c
   **/
  getEnhancedTokenData: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryStoredTokenData, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get token data with live oracle prices (backward compatibility)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0xecb3f7d0
   **/
  getTokenData: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryEnrichedTokenData, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get tokens by tier with pagination.
   * Returns up to `limit` tokens starting from `offset`.
   *
   * @param {RegistryTier} tier
   * @param {ContractCallOptions} options
   *
   * @selector 0xa50575b0
   **/
  getTokensByTier: GenericContractQueryCall<
    (
      tier: RegistryTier,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<number>, ContractCallResult>>,
    Type
  >;

  /**
   * Paginated version of get_tokens_by_tier.
   *
   * @param {RegistryTier} tier
   * @param {number} offset
   * @param {number} limit
   * @param {ContractCallOptions} options
   *
   * @selector 0x74b213cf
   **/
  getTokensByTierPaginated: GenericContractQueryCall<
    (
      tier: RegistryTier,
      offset: number,
      limit: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<number>, ContractCallResult>>,
    Type
  >;

  /**
   * Get tokens with pending tier changes
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6a6b4a70
   **/
  getTokensWithPendingChanges: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<[number, RegistryTier, RegistryTier, bigint]>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get total number of active registered tokens.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x744362af
   **/
  getTokenCount: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Get the highest token ID ever assigned (for iteration purposes).
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2f05adbb
   **/
  getMaxTokenId: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<number, ContractCallResult>>,
    Type
  >;

  /**
   * Get the owner
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07fcd0b1
   **/
  getOwner: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<H160, ContractCallResult>>,
    Type
  >;

  /**
   * Get pending owner (if any).
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x78a510ce
   **/
  getPendingOwner: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Propose ownership transfer (current owner only).
   * Initiates the two-step ownership transfer process.
   *
   * @param {H160} newOwner
   * @param {ContractCallOptions} options
   *
   * @selector 0xd8fae5bd
   **/
  proposeOwnershipTransfer: GenericContractQueryCall<
    (
      newOwner: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Accept ownership transfer (pending owner only).
   * Completes the two-step ownership transfer process.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xb55be9f0
   **/
  acceptOwnership: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Cancel pending ownership transfer (current owner only).
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x07144662
   **/
  cancelOwnershipTransfer: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Check if a token exists
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x88baeb9e
   **/
  tokenExists: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Get basic token data without oracle calls (backward compatibility)
   *
   * @param {number} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x312e4a2b
   **/
  getBasicTokenData: GenericContractQueryCall<
    (
      tokenId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<RegistryTokenData, RegistryError>,
        ContractCallResult
      >
    >,
    Type
  >;

  /**
   * Get token ID by token contract address
   *
   * @param {H160} tokenContract
   * @param {ContractCallOptions} options
   *
   * @selector 0x75e203e0
   **/
  getTokenIdByContract: GenericContractQueryCall<
    (
      tokenContract: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<number | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set portfolio contract (owner only)
   *
   * @param {H160} portfolio
   * @param {ContractCallOptions} options
   *
   * @selector 0x35760b89
   **/
  setPortfolioContract: GenericContractQueryCall<
    (
      portfolio: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set staking contract (owner only)
   *
   * @param {H160} staking
   * @param {ContractCallOptions} options
   *
   * @selector 0x00e16ab8
   **/
  setStakingContract: GenericContractQueryCall<
    (
      staking: H160,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get portfolio contract
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x677e4cf8
   **/
  getPortfolioContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get staking contract
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x01b9cd68
   **/
  getStakingContract: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<H160 | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Check if monthly rebalancing is due.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9c1b5c4c
   **/
  isRebalancingDue: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Trigger monthly rebalancing in Portfolio contract.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x29bac70c
   **/
  triggerMonthlyRebalancing: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Trigger weekly snapshot in Portfolio contract.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x6d9f90a6
   **/
  triggerWeeklySnapshot: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Trigger zombie stake cleanup in Staking contract.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xb26132ec
   **/
  triggerZombieCleanup: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Execute full monthly maintenance cycle.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x9ef3c9e2
   **/
  executeMonthlyMaintenance: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Set rebalancing interval (owner only).
   * If interval is significantly shortened, resets last trigger to allow immediate rebalance.
   *
   * @param {bigint} intervalMs
   * @param {ContractCallOptions} options
   *
   * @selector 0x8d52af0e
   **/
  setRebalancingInterval: GenericContractQueryCall<
    (
      intervalMs: bigint,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Result<[], RegistryError>, ContractCallResult>
    >,
    Type
  >;

  /**
   * Get last rebalancing trigger timestamp.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xea0bd9be
   **/
  getLastRebalancingTrigger: GenericContractQueryCall<
    (
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint | undefined, ContractCallResult>
    >,
    Type
  >;

  /**
   * Validate that a weight is within valid range (0-10000 basis points).
   *
   * @param {number} weightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0xf909b201
   **/
  validateWeight: GenericContractQueryCall<
    (
      weightBp: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Validate that a set of weights sum to exactly 100% (10000 basis points).
   *
   * @param {Array<number>} weightsBp
   * @param {ContractCallOptions} options
   *
   * @selector 0xb21c86d4
   **/
  validateWeightsSum: GenericContractQueryCall<
    (
      weightsBp: Array<number>,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;

  /**
   * Validate weight for a token update.
   * Returns error description if invalid, None if valid.
   *
   * @param {number} weightBp
   * @param {ContractCallOptions} options
   *
   * @selector 0x6c22e342
   **/
  checkWeightValidity: GenericContractQueryCall<
    (
      weightBp: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<string | undefined, ContractCallResult>
    >,
    Type
  >;
}
