// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { H160 } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from "dedot/contracts";
import type {
  RegistryRole,
  RegistryTier,
  RegistryTierThresholds,
} from "./types.js";

export interface ContractTx<
  Type extends MetadataType,
> extends GenericContractTx<Type> {
  /**
   * Grant a role to an account (owner only)
   *
   * @param {RegistryRole} role
   * @param {H160} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x2aabfab5
   **/
  grantRole: GenericContractTxCall<
    (
      role: RegistryRole,
      account: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Revoke a role from an account (owner only)
   *
   * @param {RegistryRole} role
   * @param {H160} account
   * @param {ContractTxOptions} options
   *
   * @selector 0x35e1ef4a
   **/
  revokeRole: GenericContractTxCall<
    (
      role: RegistryRole,
      account: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Add a new token to the registry with automatic tier calculation.
   * Blocked when contract is paused.
   *
   * @param {H160} tokenContract
   * @param {H160} oracleContract
   * @param {ContractTxOptions} options
   *
   * @selector 0x84731716
   **/
  addToken: GenericContractTxCall<
    (
      tokenContract: H160,
      oracleContract: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update token balance and investment data with automatic tier recalculation.
   * Blocked when contract is paused.
   *
   * @param {number} tokenId
   * @param {bigint} balance
   * @param {number} weightInvestment
   * @param {ContractTxOptions} options
   *
   * @selector 0x90c3ef3a
   **/
  updateToken: GenericContractTxCall<
    (
      tokenId: number,
      balance: bigint,
      weightInvestment: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Remove a token from the registry.
   * Blocked when contract is paused.
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0xc964c4ec
   **/
  removeToken: GenericContractTxCall<
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Manually update tier for a specific token (owner only)
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0xb11eb1ae
   **/
  updateTokenTier: GenericContractTxCall<
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Emergency tier override - bypasses grace period (owner only).
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {number} tokenId
   * @param {RegistryTier} newTier
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0xe67d97ff
   **/
  emergencyTierOverride: GenericContractTxCall<
    (
      tokenId: number,
      newTier: RegistryTier,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Emergency tier override to calculated tier - bypasses grace period (owner only)
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {number} tokenId
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x5b5a3d00
   **/
  emergencyTierOverrideToCalculated: GenericContractTxCall<
    (
      tokenId: number,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Clear pending tier change (owner only)
   *
   * @param {number} tokenId
   * @param {ContractTxOptions} options
   *
   * @selector 0x53bba34a
   **/
  clearPendingTierChange: GenericContractTxCall<
    (
      tokenId: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set grace period duration (owner only)
   *
   * @param {bigint} periodMs
   * @param {ContractTxOptions} options
   *
   * @selector 0x86200a8b
   **/
  setGracePeriod: GenericContractTxCall<
    (
      periodMs: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Batch update tiers for tokens with pagination.
   * Returns number of tokens updated in this batch.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x8646ff68
   **/
  refreshAllTiers: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Paginated version of refresh_all_tiers.
   * `offset`: number of token IDs to skip from the start (0-based),
   * `limit`: maximum number of token IDs to process.
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractTxOptions} options
   *
   * @selector 0xbae7b4f9
   **/
  refreshTiersPaginated: GenericContractTxCall<
    (
      offset: number,
      limit: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Process tokens with expired grace periods (updated to use dynamic grace period)
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x39150c26
   **/
  processGracePeriods: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Paginated grace-period processing.
   * `offset`: number of token IDs to skip from the start (0-based),
   * `limit`: maximum number of token IDs to scan.
   *
   * @param {number} offset
   * @param {number} limit
   * @param {ContractTxOptions} options
   *
   * @selector 0xa9695f4f
   **/
  processGracePeriodsPaginated: GenericContractTxCall<
    (
      offset: number,
      limit: number,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Execute tier shift (automatic or manual)
   * Manual tier shift - owner only
   * Reason parameter is truncated to MAX_REASON_LENGTH.
   *
   * @param {RegistryTier} newTier
   * @param {string} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0x71f99599
   **/
  shiftActiveTier: GenericContractTxCall<
    (
      newTier: RegistryTier,
      reason: string,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set DOT/USD oracle contract (owner only)
   *
   * @param {H160} oracleContract
   * @param {ContractTxOptions} options
   *
   * @selector 0x819b20a3
   **/
  setDotUsdOracle: GenericContractTxCall<
    (
      oracleContract: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update tier thresholds in USD (owner only)
   *
   * @param {RegistryTierThresholds} thresholds
   * @param {ContractTxOptions} options
   *
   * @selector 0xe2d49881
   **/
  setTierThresholds: GenericContractTxCall<
    (
      thresholds: RegistryTierThresholds,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Propose ownership transfer (current owner only).
   * Initiates the two-step ownership transfer process.
   *
   * @param {H160} newOwner
   * @param {ContractTxOptions} options
   *
   * @selector 0xd8fae5bd
   **/
  proposeOwnershipTransfer: GenericContractTxCall<
    (
      newOwner: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Accept ownership transfer (pending owner only).
   * Completes the two-step ownership transfer process.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xb55be9f0
   **/
  acceptOwnership: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Cancel pending ownership transfer (current owner only).
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x07144662
   **/
  cancelOwnershipTransfer: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set portfolio contract (owner only)
   *
   * @param {H160} portfolio
   * @param {ContractTxOptions} options
   *
   * @selector 0x35760b89
   **/
  setPortfolioContract: GenericContractTxCall<
    (
      portfolio: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set staking contract (owner only)
   *
   * @param {H160} staking
   * @param {ContractTxOptions} options
   *
   * @selector 0x00e16ab8
   **/
  setStakingContract: GenericContractTxCall<
    (
      staking: H160,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Trigger monthly rebalancing in Portfolio contract.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x29bac70c
   **/
  triggerMonthlyRebalancing: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Trigger weekly snapshot in Portfolio contract.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x6d9f90a6
   **/
  triggerWeeklySnapshot: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Trigger zombie stake cleanup in Staking contract.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xb26132ec
   **/
  triggerZombieCleanup: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Execute full monthly maintenance cycle.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x9ef3c9e2
   **/
  executeMonthlyMaintenance: GenericContractTxCall<
    (options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Set rebalancing interval (owner only).
   * If interval is significantly shortened, resets last trigger to allow immediate rebalance.
   *
   * @param {bigint} intervalMs
   * @param {ContractTxOptions} options
   *
   * @selector 0x8d52af0e
   **/
  setRebalancingInterval: GenericContractTxCall<
    (
      intervalMs: bigint,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;
}
