// Generated by dedot cli

import type { H160 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type RegistryStoredTokenData = {
  tokenContract: H160;
  oracleContract: H160;
  balance: bigint;
  weightInvestment: number;
  tier: RegistryTier;
  tierChangeTimestamp?: bigint | undefined;
  pendingTierChange?: RegistryTier | undefined;
};

export type RegistryTier = "None" | "Tier1" | "Tier2" | "Tier3" | "Tier4";

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type RegistryRole =
  | "TokenManager"
  | "TokenUpdater"
  | "EmergencyController";

export type Registry = {
  tokens: { get(arg: number): Promise<RegistryStoredTokenData | undefined> };
  tokenContractToId: { get(arg: H160): Promise<number | undefined> };
  roleMembers: { get(arg: [RegistryRole, H160]): Promise<boolean | undefined> };
  nextTokenId: number;
  owner: H160;
  pendingOwner?: H160 | undefined;
  paused: boolean;
  activeTier: RegistryTier;
  tierThresholds: RegistryTierThresholds;
  tierDistribution: { get(arg: RegistryTier): Promise<number | undefined> };
  lastTierChange?: bigint | undefined;
  dotUsdOracle?: H160 | undefined;
  gracePeriodMs: bigint;
  portfolioContract?: H160 | undefined;
  stakingContract?: H160 | undefined;
  lastRebalancingTrigger?: bigint | undefined;
  rebalancingIntervalMs: bigint;
  activeTokenCount: number;
};

export type RegistryTierThresholds = {
  tier1MarketCapUsd: bigint;
  tier1VolumeUsd: bigint;
  tier2MarketCapUsd: bigint;
  tier2VolumeUsd: bigint;
  tier3MarketCapUsd: bigint;
  tier3VolumeUsd: bigint;
  tier4MarketCapUsd: bigint;
  tier4VolumeUsd: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type RegistryError =
  | "Unauthorized"
  | "UnauthorizedRole"
  | "TokenNotFound"
  | "TokenAlreadyExists"
  | "InvalidTokenContract"
  | "ZeroAddress"
  | "InvalidWeight"
  | "InvalidTier"
  | "InvalidParameter"
  | "OracleCallFailed"
  | "InsufficientBalance"
  | "ContractPaused"
  | "CrossContractCallFailed"
  | "TransferFailed";

export type RegistryEnrichedTokenData = {
  tokenContract: H160;
  oracleContract: H160;
  balance: bigint;
  weightInvestment: number;
  tier: number;
  marketCap: bigint;
  marketVolume: bigint;
  price: bigint;
};

export type RegistryTokenData = {
  tokenContract: H160;
  oracleContract: H160;
  balance: bigint;
  weightInvestment: number;
  tier: number;
};
